services:
  backend:
    build:
      context: ../..
      dockerfile: infra/docker/backend.Dockerfile
    environment:
      SPM_CORS_ORIGINS: "http://localhost:8080"
      SPM_ENV: "production"
    volumes:
      - ../../src/backend/data:/app/backend/data
      - ../../src/backend/logs:/app/backend/logs
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - "5001:5000"

  frontend:
    image: nginx:alpine
    volumes:
      - ../../src/frontend:/usr/share/nginx/html:ro
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "8080:80"
